# Project language
language: php

# Choosing PHP versions to test
php:
  - '7.2'

# Commands to be run before your environment runs:
before_script:
  - composer self-update

after_success:
  - travis_retry php php-coveralls.phar
